name: Lint

on:
  pull_request: 

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
        with:
          python-version: "3.10"
      - name: Setup Matchers
        run: |
          echo "::add-matcher::.github/workflows/matchers/mypy.json"
          echo "TERM: changing from $TERM -> xterm"
          export TERM=xterm
      - name: Install dependencies
        run: pip install mypy
      - name: Run mypy
        run: mypy --show-column-numbers .

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup Matchers
        run: |
          echo "::add-matcher::.github/workflows/matchers/ruff.json"
          echo "TERM: changing from $TERM -> xterm"
          export TERM=xterm
      - name: Install dependencies
        run: pip install ruff
      - name: Run ruff
        run: ruff .
